const COLOMBIA_DATA = {
  "Antioquia": [
    "Abejorral",
    "Abriaquí",
    "Alejandría",
    "Amagá",
    "Amalfi",
    "Andes",
    "Angelópolis",
    "Angostura",
    "Anorí",
    "Anza",
    "Apartadó",
    "Arboletes",
    "Argelia",
    "Armenia",
    "Barbosa",
    "Bello",
    "Belmira",
    "Betania",
    "Betulia",
    "Briceño",
    "Buriticá",
    "Caicedo",
    "Caldas",
    "Campamento",
    "Caracolí",
    "Caramanta",
    "Carepa",
    "Carolina",
    "Caucasia",
    "Cañasgordas",
    "Chigorodó",
    "Cisneros",
    "Ciudad Bolívar",
    "Cocorná",
    "Concepción",
    "Concordia",
    "Copacabana",
    "Cáceres",
    "Dabeiba",
    "Don Matías",
    "Ebéjico",
    "El Bagre",
    "El Carmen de Viboral",
    "El Santuario",
    "Entrerrios",
    "Envigado",
    "Fredonia",
    "Frontino",
    "Giraldo",
    "Girardota",
    "Granada",
    "Guadalupe",
    "Guarne",
    "Guatapé",
    "Gómez Plata",
    "Heliconia",
    "Hispania",
    "Itagui",
    "Ituango",
    "Jardín",
    "Jericó",
    "La Ceja",
    "La Estrella",
    "La Pintada",
    "La Unión",
    "Liborina",
    "Maceo",
    "Marinilla",
    "Medellín",
    "Montebello",
    "Murindó",
    "Mutatá",
    "Nariño",
    "Nechí",
    "Necoclí",
    "Olaya",
    "Peque",
    "Peñol",
    "Pueblorrico",
    "Puerto Berrío",
    "Puerto Nare",
    "Puerto Triunfo",
    "Remedios",
    "Retiro",
    "Rionegro",
    "Sabanalarga",
    "Sabaneta",
    "Salgar",
    "San Andrés de Cuerquía",
    "San Carlos",
    "San Francisco",
    "San Jerónimo",
    "San José de La Montaña",
    "San Juan de Urabá",
    "San Luis",
    "San Pedro",
    "San Pedro de Uraba",
    "San Rafael",
    "San Roque",
    "San Vicente",
    "Santa Bárbara",
    "Santa Rosa de Osos",
    "Santafé de Antioquia",
    "Santo Domingo",
    "Segovia",
    "Sonsón",
    "Sopetrán",
    "Tarazá",
    "Tarso",
    "Titiribí",
    "Toledo",
    "Turbo",
    "Támesis",
    "Uramita",
    "Urrao",
    "Valdivia",
    "Valparaíso",
    "Vegachí",
    "Venecia",
    "Vigía del Fuerte",
    "Yalí",
    "Yarumal",
    "Yolombó",
    "Yondó",
    "Zaragoza"
  ],
  "Atlántico": [
    "Baranoa",
    "Barranquilla",
    "Campo de La Cruz",
    "Candelaria",
    "Galapa",
    "Juan de Acosta",
    "Luruaco",
    "Malambo",
    "Manatí",
    "Palmar de Varela",
    "Piojó",
    "Polonuevo",
    "Ponedera",
    "Puerto Colombia",
    "Repelón",
    "Sabanagrande",
    "Sabanalarga",
    "Santa Lucía",
    "Santo Tomás",
    "Soledad",
    "Suan",
    "Tubará",
    "Usiacurí"
  ],
  "Bogotá D.C.": [
    "Bogotá D.C."
  ],
  "Bolívar": [
    "Achí",
    "Altos del Rosario",
    "Arenal",
    "Arjona",
    "Arroyohondo",
    "Barranco de Loba",
    "Calamar",
    "Cantagallo",
    "Cartagena",
    "Cicuco",
    "Clemencia",
    "Córdoba",
    "El Carmen de Bolívar",
    "El Guamo",
    "El Peñón",
    "Hatillo de Loba",
    "Magangué",
    "Mahates",
    "Margarita",
    "María la Baja",
    "Mompós",
    "Montecristo",
    "Morales",
    "Norosí",
    "Pinillos",
    "Regidor",
    "Río Viejo",
    "San Cristóbal",
    "San Estanislao",
    "San Fernando",
    "San Jacinto",
    "San Jacinto del Cauca",
    "San Juan Nepomuceno",
    "San Martín de Loba",
    "San Pablo de Borbur",
    "Santa Catalina",
    "Santa Rosa",
    "Santa Rosa del Sur",
    "Simití",
    "Soplaviento",
    "Talaigua Nuevo",
    "Tiquisio",
    "Turbaco",
    "Turbaná",
    "Villanueva",
    "Zambrano"
  ],
  "Boyacá": [
    "Almeida",
    "Aquitania",
    "Arcabuco",
    "Belén",
    "Berbeo",
    "Betéitiva",
    "Boavita",
    "Boyacá",
    "Briceño",
    "Buena Vista",
    "Busbanzá",
    "Caldas",
    "Campohermoso",
    "Cerinza",
    "Chinavita",
    "Chiquinquirá",
    "Chiscas",
    "Chita",
    "Chitaraque",
    "Chivatá",
    "Chivor",
    "Chíquiza",
    "Ciénega",
    "Coper",
    "Corrales",
    "Covarachía",
    "Cubará",
    "Cucaita",
    "Cuítiva",
    "Cómbita",
    "Duitama",
    "El Cocuy",
    "El Espino",
    "Firavitoba",
    "Floresta",
    "Gachantivá",
    "Gameza",
    "Garagoa",
    "Guacamayas",
    "Guateque",
    "Guayatá",
    "Güicán",
    "Iza",
    "Jenesano",
    "Jericó",
    "La Capilla",
    "La Uvita",
    "La Victoria",
    "Labranzagrande",
    "Macanal",
    "Maripí",
    "Miraflores",
    "Mongua",
    "Monguí",
    "Moniquirá",
    "Motavita",
    "Muzo",
    "Nobsa",
    "Nuevo Colón",
    "Oicatá",
    "Otanche",
    "Pachavita",
    "Paipa",
    "Pajarito",
    "Panqueba",
    "Pauna",
    "Paya",
    "Paz de Río",
    "Pesca",
    "Pisba",
    "Puerto Boyacá",
    "Páez",
    "Quípama",
    "Ramiriquí",
    "Rondón",
    "Ráquira",
    "Saboyá",
    "Samacá",
    "San Eduardo",
    "San José de Pare",
    "San Luis de Gaceno",
    "San Mateo",
    "San Miguel de Sema",
    "San Pablo de Borbur",
    "Santa María",
    "Santa Rosa de Viterbo",
    "Santa Sofía",
    "Santana",
    "Sativanorte",
    "Sativasur",
    "Siachoque",
    "Soatá",
    "Socha",
    "Socotá",
    "Sogamoso",
    "Somondoco",
    "Sora",
    "Soracá",
    "Sotaquirá",
    "Susacón",
    "Sutamarchán",
    "Sutatenza",
    "Sáchica",
    "Tasco",
    "Tenza",
    "Tibaná",
    "Tibasosa",
    "Tinjacá",
    "Tipacoque",
    "Toca",
    "Togüí",
    "Tota",
    "Tunja",
    "Tununguá",
    "Turmequé",
    "Tuta",
    "Tutazá",
    "Tópaga",
    "Umbita",
    "Ventaquemada",
    "Villa de Leyva",
    "Viracachá",
    "Zetaquira"
  ],
  "Caldas": [
    "Aguadas",
    "Anserma",
    "Aranzazu",
    "Belalcázar",
    "Chinchiná",
    "Filadelfia",
    "La Dorada",
    "La Merced",
    "Manizales",
    "Manzanares",
    "Marmato",
    "Marquetalia",
    "Marulanda",
    "Neira",
    "Norcasia",
    "Palestina",
    "Pensilvania",
    "Pácora",
    "Riosucio",
    "Risaralda",
    "Salamina",
    "Samaná",
    "San José",
    "Supía",
    "Victoria",
    "Villamaría",
    "Viterbo"
  ],
  "Caquetá": [
    "Albania",
    "Belén de Los Andaquies",
    "Cartagena del Chairá",
    "Curillo",
    "El Doncello",
    "El Paujil",
    "Florencia",
    "La Montañita",
    "Milán",
    "Morelia",
    "Puerto Rico",
    "San José del Fragua",
    "San Vicente del Caguán",
    "Solano",
    "Solita",
    "Valparaíso"
  ],
  "Cauca": [
    "Almaguer",
    "Argelia",
    "Balboa",
    "Bolívar",
    "Buenos Aires",
    "Cajibío",
    "Caldono",
    "Caloto",
    "Corinto",
    "El Tambo",
    "Florencia",
    "Guachené",
    "Guapi",
    "Inzá",
    "Jambaló",
    "La Sierra",
    "La Vega",
    "López",
    "Mercaderes",
    "Miranda",
    "Morales",
    "Padilla",
    "Patía",
    "Piamonte",
    "Piendamó",
    "Popayán",
    "Puerto Tejada",
    "Puracé",
    "Páez",
    "Rosas",
    "San Sebastián",
    "Santa Rosa",
    "Santander de Quilichao",
    "Silvia",
    "Sotara",
    "Sucre",
    "Suárez",
    "Timbiquí",
    "Timbío",
    "Toribio",
    "Totoró",
    "Villa Rica"
  ],
  "Cesar": [
    "Aguachica",
    "Agustín Codazzi",
    "Astrea",
    "Becerril",
    "Bosconia",
    "Chimichagua",
    "Chiriguaná",
    "Curumaní",
    "El Copey",
    "El Paso",
    "Gamarra",
    "González",
    "La Gloria",
    "La Jagua de Ibirico",
    "La Paz",
    "Manaure",
    "Pailitas",
    "Pelaya",
    "Pueblo Bello",
    "Río de Oro",
    "San Alberto",
    "San Diego",
    "San Martín",
    "Tamalameque",
    "Valledupar"
  ],
  "Córdoba": [
    "Ayapel",
    "Buenavista",
    "Canalete",
    "Cereté",
    "Chimá",
    "Chinú",
    "Ciénaga de Oro",
    "Cotorra",
    "La Apartada",
    "Lorica",
    "Los Córdobas",
    "Momil",
    "Montelíbano",
    "Montería",
    "Moñitos",
    "Planeta Rica",
    "Pueblo Nuevo",
    "Puerto Escondido",
    "Puerto Libertador",
    "Purísima",
    "Sahagún",
    "San Andrés Sotavento",
    "San Antero",
    "San Bernardo del Viento",
    "San Carlos",
    "San José de Uré",
    "San Pelayo",
    "Tierralta",
    "Tuchín",
    "Valencia"
  ],
  "Cundinamarca": [
    "Agua de Dios",
    "Albán",
    "Anapoima",
    "Anolaima",
    "Apulo",
    "Arbeláez",
    "Beltrán",
    "Bituima",
    "Bojacá",
    "Cabrera",
    "Cachipay",
    "Cajicá",
    "Caparrapí",
    "Caqueza",
    "Carmen de Carupa",
    "Chaguaní",
    "Chipaque",
    "Choachí",
    "Chocontá",
    "Chía",
    "Cogua",
    "Cota",
    "Cucunubá",
    "El Colegio",
    "El Peñón",
    "El Rosal",
    "Facatativá",
    "Fomeque",
    "Fosca",
    "Funza",
    "Fusagasugá",
    "Fúquene",
    "Gachala",
    "Gachancipá",
    "Gachetá",
    "Gama",
    "Girardot",
    "Granada",
    "Guachetá",
    "Guaduas",
    "Guasca",
    "Guataquí",
    "Guatavita",
    "Guayabal de Siquima",
    "Guayabetal",
    "Gutiérrez",
    "Jerusalén",
    "Junín",
    "La Calera",
    "La Mesa",
    "La Palma",
    "La Peña",
    "La Vega",
    "Lenguazaque",
    "Macheta",
    "Madrid",
    "Manta",
    "Medina",
    "Mosquera",
    "Nariño",
    "Nemocón",
    "Nilo",
    "Nimaima",
    "Nocaima",
    "Pacho",
    "Paime",
    "Pandi",
    "Paratebueno",
    "Pasca",
    "Puerto Salgar",
    "Pulí",
    "Quebradanegra",
    "Quetame",
    "Quipile",
    "Ricaurte",
    "San Antonio del Tequendama",
    "San Bernardo",
    "San Cayetano",
    "San Francisco",
    "San Juan de Río Seco",
    "Sasaima",
    "Sesquilé",
    "Sibaté",
    "Silvania",
    "Simijaca",
    "Soacha",
    "Sopó",
    "Subachoque",
    "Suesca",
    "Supatá",
    "Susa",
    "Sutatausa",
    "Tabio",
    "Tausa",
    "Tena",
    "Tenjo",
    "Tibacuy",
    "Tibirita",
    "Tocaima",
    "Tocancipá",
    "Topaipí",
    "Ubalá",
    "Ubaque",
    "Une",
    "Venecia",
    "Vergara",
    "Vianí",
    "Villa de San Diego de Ubate",
    "Villagómez",
    "Villapinzón",
    "Villeta",
    "Viotá",
    "Yacopí",
    "Zipacón",
    "Zipaquirá",
    "Útica"
  ],
  "Chocó": [
    "Acandí",
    "Alto Baudo",
    "Atrato",
    "Bagadó",
    "Bahía Solano",
    "Bajo Baudó",
    "Belén de Bajira",
    "Bojaya",
    "Carmen del Darien",
    "Condoto",
    "Cértegui",
    "El Cantón del San Pablo",
    "El Carmen de Atrato",
    "El Litoral del San Juan",
    "Istmina",
    "Juradó",
    "Lloró",
    "Medio Atrato",
    "Medio Baudó",
    "Medio San Juan",
    "Nuquí",
    "Nóvita",
    "Quibdó",
    "Riosucio",
    "Río Iro",
    "Río Quito",
    "San José del Palmar",
    "Sipí",
    "Tadó",
    "Unguía",
    "Unión Panamericana"
  ],
  "Huila": [
    "Acevedo",
    "Agrado",
    "Aipe",
    "Algeciras",
    "Altamira",
    "Baraya",
    "Campoalegre",
    "Colombia",
    "Elías",
    "Garzón",
    "Gigante",
    "Guadalupe",
    "Hobo",
    "Iquira",
    "Isnos",
    "La Argentina",
    "La Plata",
    "Neiva",
    "Nátaga",
    "Oporapa",
    "Paicol",
    "Palermo",
    "Palestina",
    "Pital",
    "Pitalito",
    "Rivera",
    "Saladoblanco",
    "San Agustín",
    "Santa María",
    "Suaza",
    "Tarqui",
    "Tello",
    "Teruel",
    "Tesalia",
    "Timaná",
    "Villavieja",
    "Yaguará"
  ],
  "La Guajira": [
    "Albania",
    "Barrancas",
    "Dibula",
    "Distracción",
    "El Molino",
    "Fonseca",
    "Hatonuevo",
    "La Jagua del Pilar",
    "Maicao",
    "Manaure",
    "Riohacha",
    "San Juan del Cesar",
    "Uribia",
    "Urumita",
    "Villanueva"
  ],
  "Magdalena": [
    "Algarrobo",
    "Aracataca",
    "Ariguaní",
    "Cerro San Antonio",
    "Chivolo",
    "Ciénaga",
    "Concordia",
    "El Banco",
    "El Piñon",
    "El Retén",
    "Fundación",
    "Guamal",
    "Nueva Granada",
    "Pedraza",
    "Pijiño del Carmen",
    "Pivijay",
    "Plato",
    "Pueblo Viejo",
    "Remolino",
    "Sabanas de San Angel",
    "Salamina",
    "San Sebastián de Buenavista",
    "San Zenón",
    "Santa Ana",
    "Santa Bárbara de Pinto",
    "Santa Marta",
    "Sitionuevo",
    "Tenerife",
    "Zapayán",
    "Zona Bananera"
  ],
  "Meta": [
    "Acacias",
    "Barranca de Upía",
    "Cabuyaro",
    "Castilla la Nueva",
    "Cubarral",
    "Cumaral",
    "El Calvario",
    "El Castillo",
    "El Dorado",
    "Fuente de Oro",
    "Granada",
    "Guamal",
    "La Macarena",
    "Lejanías",
    "Mapiripán",
    "Mesetas",
    "Puerto Concordia",
    "Puerto Gaitán",
    "Puerto Lleras",
    "Puerto López",
    "Puerto Rico",
    "Restrepo",
    "San Carlos de Guaroa",
    "San Juan de Arama",
    "San Juanito",
    "San Martín",
    "Uribe",
    "Villavicencio",
    "Vista Hermosa"
  ],
  "Nariño": [
    "Albán",
    "Aldana",
    "Ancuyá",
    "Arboleda",
    "Barbacoas",
    "Belén",
    "Buesaco",
    "Chachagüí",
    "Colón",
    "Consaca",
    "Contadero",
    "Cuaspud",
    "Cumbal",
    "Cumbitara",
    "Córdoba",
    "El Charco",
    "El Peñol",
    "El Rosario",
    "El Tablón de Gómez",
    "El Tambo",
    "Francisco Pizarro",
    "Funes",
    "Guachucal",
    "Guaitarilla",
    "Gualmatán",
    "Iles",
    "Imués",
    "Ipiales",
    "La Cruz",
    "La Florida",
    "La Llanada",
    "La Tola",
    "La Unión",
    "Leiva",
    "Linares",
    "Los Andes",
    "Magüí",
    "Mallama",
    "Mosquera",
    "Nariño",
    "Olaya Herrera",
    "Ospina",
    "Pasto",
    "Policarpa",
    "Potosí",
    "Providencia",
    "Puerres",
    "Pupiales",
    "Ricaurte",
    "Roberto Payán",
    "Samaniego",
    "San Andrés de Tumaco",
    "San Bernardo",
    "San Lorenzo",
    "San Pablo",
    "San Pedro de Cartago",
    "Sandoná",
    "Santa Bárbara",
    "Santacruz",
    "Sapuyes",
    "Taminango",
    "Tangua",
    "Túquerres",
    "Yacuanquer"
  ],
  "Norte de Santander": [
    "Abrego",
    "Arboledas",
    "Bochalema",
    "Bucarasica",
    "Cachirá",
    "Chinácota",
    "Chitagá",
    "Convención",
    "Cucutilla",
    "Cácota",
    "Cúcuta",
    "Durania",
    "El Carmen",
    "El Tarra",
    "El Zulia",
    "Gramalote",
    "Hacarí",
    "Herrán",
    "La Esperanza",
    "La Playa",
    "Labateca",
    "Los Patios",
    "Lourdes",
    "Mutiscua",
    "Ocaña",
    "Pamplona",
    "Pamplonita",
    "Puerto Santander",
    "Ragonvalia",
    "Salazar",
    "San Calixto",
    "San Cayetano",
    "Santiago",
    "Sardinata",
    "Silos",
    "Teorama",
    "Tibú",
    "Toledo",
    "Villa Caro",
    "Villa del Rosario"
  ],
  "Quindío": [
    "Armenia",
    "Buenavista",
    "Calarcá",
    "Circasia",
    "Córdoba",
    "Filandia",
    "Génova",
    "La Tebaida",
    "Montenegro",
    "Pijao",
    "Quimbaya",
    "Salento"
  ],
  "Risaralda": [
    "Apía",
    "Balboa",
    "Belén de Umbría",
    "Dosquebradas",
    "Guática",
    "La Celia",
    "La Virginia",
    "Marsella",
    "Mistrató",
    "Pereira",
    "Pueblo Rico",
    "Quinchía",
    "Santa Rosa de Cabal",
    "Santuario"
  ],
  "Santander": [
    "Aguada",
    "Albania",
    "Aratoca",
    "Barbosa",
    "Barichara",
    "Barrancabermeja",
    "Betulia",
    "Bolívar",
    "Bucaramanga",
    "Cabrera",
    "California",
    "Capitanejo",
    "Carcasí",
    "Cepitá",
    "Cerrito",
    "Charalá",
    "Charta",
    "Chimá",
    "Chipatá",
    "Cimitarra",
    "Concepción",
    "Confines",
    "Contratación",
    "Coromoro",
    "Curití",
    "El Carmen de Chucurí",
    "El Guacamayo",
    "El Peñón",
    "El Playón",
    "Encino",
    "Enciso",
    "Floridablanca",
    "Florián",
    "Galán",
    "Gambita",
    "Girón",
    "Guaca",
    "Guadalupe",
    "Guapotá",
    "Guavatá",
    "Güepsa",
    "Hato",
    "Jesús María",
    "Jordán",
    "La Belleza",
    "La Paz",
    "Landázuri",
    "Lebríja",
    "Los Santos",
    "Macaravita",
    "Matanza",
    "Mogotes",
    "Molagavita",
    "Málaga",
    "Ocamonte",
    "Oiba",
    "Onzaga",
    "Palmar",
    "Palmas del Socorro",
    "Piedecuesta",
    "Pinchote",
    "Puente Nacional",
    "Puerto Parra",
    "Puerto Wilches",
    "Páramo",
    "Rionegro",
    "Sabana de Torres",
    "San Andrés",
    "San Benito",
    "San Gil",
    "San Joaquín",
    "San José de Miranda",
    "San Miguel",
    "San Vicente de Chucurí",
    "Santa Bárbara",
    "Santa Helena del Opón",
    "Simacota",
    "Socorro",
    "Suaita",
    "Sucre",
    "Suratá",
    "Tona",
    "Valle de San José",
    "Vetas",
    "Villanueva",
    "Vélez",
    "Zapatoca"
  ],
  "Sucre": [
    "Buenavista",
    "Caimito",
    "Chalán",
    "Coloso",
    "Corozal",
    "Coveñas",
    "El Roble",
    "Galeras",
    "Guaranda",
    "La Unión",
    "Los Palmitos",
    "Majagual",
    "Morroa",
    "Ovejas",
    "Palmito",
    "Sampués",
    "San Benito Abad",
    "San Juan de Betulia",
    "San Luis de Sincé",
    "San Marcos",
    "San Onofre",
    "San Pedro",
    "Santiago de Tolú",
    "Sincelejo",
    "Sucre",
    "Tolú Viejo"
  ],
  "Tolima": [
    "Alpujarra",
    "Alvarado",
    "Ambalema",
    "Anzoátegui",
    "Armero",
    "Ataco",
    "Cajamarca",
    "Carmen de Apicala",
    "Casabianca",
    "Chaparral",
    "Coello",
    "Coyaima",
    "Cunday",
    "Dolores",
    "Espinal",
    "Falan",
    "Flandes",
    "Fresno",
    "Guamo",
    "Herveo",
    "Honda",
    "Ibagué",
    "Icononzo",
    "Lérida",
    "Líbano",
    "Mariquita",
    "Melgar",
    "Murillo",
    "Natagaima",
    "Ortega",
    "Palocabildo",
    "Piedras",
    "Planadas",
    "Prado",
    "Purificación",
    "Rio Blanco",
    "Roncesvalles",
    "Rovira",
    "Saldaña",
    "San Antonio",
    "San Luis",
    "Santa Isabel",
    "Suárez",
    "Valle de San Juan",
    "Venadillo",
    "Villahermosa",
    "Villarrica"
  ],
  "Valle del Cauca": [
    "Alcalá",
    "Andalucía",
    "Ansermanuevo",
    "Argelia",
    "Bolívar",
    "Buenaventura",
    "Bugalagrande",
    "Caicedonia",
    "Cali",
    "Calima",
    "Candelaria",
    "Cartago",
    "Dagua",
    "El Cairo",
    "El Cerrito",
    "El Dovio",
    "El Águila",
    "Florida",
    "Ginebra",
    "Guacarí",
    "Guadalajara de Buga",
    "Jamundí",
    "La Cumbre",
    "La Unión",
    "La Victoria",
    "Obando",
    "Palmira",
    "Pradera",
    "Restrepo",
    "Riofrío",
    "Roldanillo",
    "San Pedro",
    "Sevilla",
    "Toro",
    "Trujillo",
    "Tuluá",
    "Ulloa",
    "Versalles",
    "Vijes",
    "Yotoco",
    "Yumbo",
    "Zarzal"
  ],
  "Arauca": [
    "Arauca",
    "Arauquita",
    "Cravo Norte",
    "Fortul",
    "Puerto Rondón",
    "Saravena",
    "Tame"
  ],
  "Casanare": [
    "Aguazul",
    "Chámeza",
    "Hato Corozal",
    "La Salina",
    "Maní",
    "Monterrey",
    "Nunchía",
    "Orocué",
    "Paz de Ariporo",
    "Pore",
    "Recetor",
    "Sabanalarga",
    "San Luis de Gaceno",
    "Sácama",
    "Tauramena",
    "Trinidad",
    "Támara",
    "Villanueva",
    "Yopal"
  ],
  "Putumayo": [
    "Colón",
    "Leguízamo",
    "Mocoa",
    "Orito",
    "Puerto Asís",
    "Puerto Caicedo",
    "Puerto Guzmán",
    "San Francisco",
    "San Miguel",
    "Santiago",
    "Sibundoy",
    "Valle de Guamez",
    "Villagarzón"
  ],
  "Archipiélago de San Andrés, Providencia y Santa Catalina": [
    "Providencia",
    "San Andrés"
  ],
  "Amazonas": [
    "El Encanto",
    "La Chorrera",
    "La Pedrera",
    "La Victoria",
    "Leticia",
    "Miriti Paraná",
    "Puerto Alegría",
    "Puerto Arica",
    "Puerto Nariño",
    "Puerto Santander",
    "Tarapacá"
  ],
  "Guainía": [
    "Barranco Minas",
    "Cacahual",
    "Inírida",
    "La Guadalupe",
    "Mapiripana",
    "Morichal",
    "Pana Pana",
    "Puerto Colombia",
    "San Felipe"
  ],
  "Guaviare": [
    "Calamar",
    "El Retorno",
    "Miraflores",
    "San José del Guaviare"
  ],
  "Vaupés": [
    "Caruru",
    "Mitú",
    "Pacoa",
    "Papunaua",
    "Taraira",
    "Yavaraté"
  ],
  "Vichada": [
    "Cumaribo",
    "La Primavera",
    "Puerto Carreño",
    "Santa Rosalía"
  ]
};